"""Pre-materialize Tier 0/1 context into static files for zero-latency injection."""
from __future__ import annotations

import sqlite3
from pathlib import Path

_TIER0_TOKEN_BUDGET = 4000
_TIER1_TOKEN_BUDGET = 8000


def _load_content(workspace_root: Path, path: str) -> str:
    full = workspace_root / path
    if not full.exists():
        return ""
    from .okf import parse

    _, body = parse(full)
    return body


def materialize_tier0(
    conn: sqlite3.Connection,
    workspace_root: Path,
    out_path: Path,
) -> int:
    """
    Assemble Tier 0 context (feedback + project-state + skill items with
    highest PageRank) into a static markdown file. Returns token estimate.
    """
    rows = conn.execute(
        """
        SELECT path, title, type, tokens
        FROM knowledge_items
        WHERE tier = 1
          AND visibility = 'shared'
        ORDER BY type, tokens
        """
    ).fetchall()

    sections: list[str] = []
    total_tokens = 0

    for row in rows:
        cost = row["tokens"] or 300
        if total_tokens + cost > _TIER0_TOKEN_BUDGET:
            break
        content = _load_content(workspace_root, row["path"])
        if content:
            header = f"### [{row['type']}] {row['title'] or row['path']}"
            sections.append(f"{header}\n\n{content}")
            total_tokens += cost

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        "<!-- WKP Tier 0 — generated by wkp materialize -->\n\n"
        + "\n\n---\n\n".join(sections),
        encoding="utf-8",
    )
    return total_tokens


def materialize_tier1(
    conn: sqlite3.Connection,
    workspace_root: Path,
    out_path: Path,
) -> int:
    """
    Assemble Tier 1 index (titles + one-line descriptions only, no full content).
    Designed to be injected at session start as a lightweight routing map.
    """
    rows = conn.execute(
        """
        SELECT path, title, type, workspace, tokens
        FROM knowledge_items
        WHERE visibility = 'shared'
        ORDER BY tier, type, workspace, path
        """
    ).fetchall()

    lines: list[str] = ["## WKP Knowledge Index (Tier 1)\n"]
    total_tokens = 0

    current_workspace = None
    for row in rows:
        if row["workspace"] != current_workspace:
            current_workspace = row["workspace"]
            lines.append(f"\n### Workspace: {current_workspace or 'root'}\n")

        token_hint = f" (~{row['tokens']}t)" if row["tokens"] else ""
        lines.append(
            f"- `[{row['type'] or '?'}]` **{row['title'] or row['path']}**"
            f"{token_hint} — `{row['path']}`"
        )
        total_tokens += 8  # index line is cheap

        if total_tokens > _TIER1_TOKEN_BUDGET:
            lines.append("\n_(index truncated at token budget)_")
            break

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return total_tokens


def generate_session_hook(
    wkp_dir: Path,
    framework: str = "claude_code",
) -> str:
    """Return the text of a SessionStart hook script for the given framework.

    The hook injects the pre-materialized Tier 0 file as context before the
    first prompt. Run `wkp materialize --tier 0` to regenerate the file after
    knowledge changes.
    """
    if framework == "claude_code":
        # Use absolute path so the hook works regardless of cwd at invocation time.
        tier0_abs = (wkp_dir / "tier0.md").resolve()
        workspace_abs = wkp_dir.parent.resolve()
        return f"""\
#!/bin/bash
# WKP SessionStart hook — re-indexes changed files, then injects Tier 0 context.
# Generated by: wkp hooks --framework claude_code
# Stdout is prepended to the conversation before the first prompt.

# Re-index any files changed since the last run (SHA check skips unchanged files).
# This keeps the index current for workspaces where git commits are infrequent.
wkp index --quiet --workspace "{workspace_abs}" 2>/dev/null || true

# Regenerate Tier 0 in case Tier 1 items changed.
wkp materialize --tier 0 --workspace "{workspace_abs}" 2>/dev/null || true

TIER0="{tier0_abs}"
if [ -f "$TIER0" ]; then
  echo "<wkp-context tier=\\"0\\">"
  cat "$TIER0"
  echo "</wkp-context>"
fi
"""
    raise ValueError(f"Unknown framework: {framework}")


def generate_post_commit_hook() -> str:
    """Return text of a post-commit hook that incrementally re-indexes changed files.

    Requires `wkp` on PATH (install with `pip install agent-wkp` or `pipx install agent-wkp`).
    The hook runs from the git repo root, so `wkp` will auto-detect the workspace.
    """
    return """\
#!/bin/bash
# WKP post-commit hook — incremental index + Tier 0 regeneration.
# Generated by: wkp hooks --post-commit
# Requires: wkp on PATH

set -euo pipefail

# Find markdown files changed in this commit
changed=$(git diff --name-only HEAD~1 HEAD 2>/dev/null | grep '\\.md$' || true)

if [ -z "$changed" ]; then
  exit 0
fi

echo "[wkp] Indexing changed files..."
# Pass changed files as arguments — wkp index skips unchanged files via git blob SHA
wkp index $changed

echo "[wkp] Regenerating Tier 0..."
wkp materialize --tier 0
"""
